name: pzero
channels:
  - loop3d
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy
  - matplotlib
  - numpy
  - pandas
  - cmocean
  - colorcet
  - shapely
  - xarray
  - geopandas
  - rasterio
  - pyvistaqt
  - vedo
  - pyvista
  - ezdxf
  - laspy
  - loopstructural
