name: pzero
channels:
  - loop3d
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - rasterio
  - xarray
  - scipy
  - matplotlib
  - geopandas
  - shapely
  - vedo
  - pyvistaqt
  - pyvista
  - laspy
  - ezdxf
  - loopstructural
  - cmocean
  - colorcet
  - mplstereonet
  - pythreejs
  - pyinstaller
  - lxml
