name: pzero
channels:
  - loop3d
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  
  - vtk>9.2
  - geopandas=0.10
  - pyqt=5.15
  - rasterio=1.2
  - shapely=1.8
  - pandas<2
  - xarray
  - vedo
  - pyvista
  - pyvistaqt
  - loopstructural

  - cmocean
  - colorcet
  - mplstereonet
  - laspy
  - ezdxf
  - lxml
  - openpyxl
  - pythreejs
  - pyinstaller
  - scipy
  - matplotlib

  - pytest
  - seaborn
  - sphinx
  - sphinx_rtd_theme
