name: pzero
channels:
  - loop3d
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - geopandas=0.11.1
  - vtk=9.2.6
  - pyqt=5.15.7
  - pyvistaqt=0.10.0
  - rasterio=1.3.6
  - vedo=2023.4.4
  - loopstructural=v1.5.10
  - cmocean=3.0.3
  - colorcet=3.0.1
  - mplstereonet=0.6.2
  - seaborn=0.12.2
  - laspy=2.3.0
  - ezdxf=1.0.3
  - lxml=4.9.2
  - openpyxl=3.1.2
  - pythreejs=2.4.2
  - xarray=2023.1.0
  - pytest=7.3.1
  - sphinx=5.3.0
  - sphinx_rtd_theme=1.2.0
  - pyinstaller=5.10.1

