name: pzero
channels:
  - conda-forge
  - loop3d
  - defaults
dependencies:
  - python=3.8.17
  - geopandas=0.13.2
  - shapely=2.0.1
  - pyside6=6.5.1
  - qtpy=2.3.1
  - vtk=9.2.6
  - pyvistaqt=0.10.0
  - rasterio=1.3.7
  - vedo=2023.4.4
  - loopstructural=v1.5.10
  - cmocean=3.0.3
  - colorcet=3.0.1
  - ezdxf=1.0.3
  - laspy=2.3.0
  - lxml=4.9.2
  - mplstereonet=0.6.2
  - openpyxl=3.1.2
  - pythreejs=2.4.2
  - seaborn=0.12.2
  - xarray=2023.1.0
  - pytest=7.3.2
  - sphinx=6.2.1
  - sphinx_rtd_theme=1.2.2
  - pyinstaller=5.12.0
  