name: pzero
channels:
  - conda-forge
  - loop3d
  - defaults
dependencies:
  - python=3.8
  - blackd
  - cmocean
  - colorcet
  - ezdxf
  - geopandas
  - laspy
  - loopstructural
  - lxml
  - mplstereonet
  - openpyxl
  - pyinstaller
  - pyqt
  - pytest
  - pythreejs
  - pyvistaqt
  - qtpy
  - rasterio
  - seaborn
  - shapely=1.8
  - sphinx
  - sphinx_rtd_theme
  - vedo
  - vtk
  - xarray
