name: Deploy and Release

on:
    push:
      tags:
        - v*.*.*

jobs:
    # Specify the reusable workflow
    testing:
      uses: ./.github/workflows/release-testing.yml

    deploy-linux:
        strategy:
            matrix:
              # OS we can use to run jobs
              os: [windows-latest, ubuntu-latest, macos-latest]

        runs-on: ${{ matrix.os }}
        # Requiring one or more reusable workflows in needs
        needs: [testing]

        # Steps for deploying a release
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Install Conda Env for Linux or Windows
              if: ${{ matrix.os != 'macos-latest' }}
              uses: conda-incubator/setup-miniconda@v2
              with:
                mamba-version: "*"
                channels: conda-forge,defaults
                channel-priority: true
                activate-environment: pzero-testing
                environment-file: envs/std-environment.yml
                python-version: 3.8.16
                auto-activate-base: false

            - name: Install Conda Env for MacOS
              if: ${{ matrix.os == 'macos-latest' }}
              uses: conda-incubator/setup-miniconda@v2
              with:
                mamba-version: "*"
                channels: conda-forge,defaults
                channel-priority: true
                activate-environment: pzero-testing
                environment-file: envs/macos-environment.yml
                python-version: 3.8.16
                auto-activate-base: false


            - name: Make executable
              run: |
                pyinstaller pzero.spec
                ls

            - name: check path
              run: |
                cd installers
                ls

            - name: Upload Windows Build
              if: ${{ matrix.os == 'windows-latest' }}
              uses: actions/upload-artifact@v3
              with:
                 name: ${{ matrix.os }} build
                 path: installers/PZero_Windows


            - name: Upload Ubuntu Build
              if: ${{ matrix.os == 'ubuntu-latest' }}
              uses: actions/upload-artifact@v3
              with:
                 name: ${{ matrix.os }} build
                 path: installers/PZero_Linux


            - name: Upload MacOs Build
              if: ${{ matrix.os == 'macos-latest' }}
              uses: actions/upload-artifact@v3
              with:
                 name: ${{ matrix.os }} build
                 path: installers/PZero_Darwin