name: Release Testing

on:
  push:
    tags:
      - t*.*.*

jobs:
  # Linux
  linux-testing:
    name: Linux Unit Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    permissions:
      checks: write
      pull-requests: write


    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

