name: Deploy and Release

on:
    push:
      branches:
        - 'test_release'

jobs:
    deploy:
        strategy:
            matrix:
              # OS we can use to run jobs
              os: [ubuntu-latest, macos-latest]

        runs-on: ${{ matrix.os }}
        # Steps for deploying a release
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3


            - name: Make executable Linux
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                python3 -m pip install rasterio
                python3 -m pip install PyQt5
                python3 -m pip install pyinstaller
                pyinstaller pzero.spec
                ls

            - name: Make executable Linux
              if: ${{ matrix.os == 'macos-latest' }}
              run: |
                python3 -m pip install rasterio
                python3 -m pip install PyQt5
                python3 -m pip install pyinstaller
                pyinstaller pzero-macos.spec
                ls

            - name: check path
              run: |
                cd installers
                ls

            - name: Upload Ubuntu Build
              if: ${{ matrix.os == 'ubuntu-latest' }}
              uses: actions/upload-artifact@v3
              with:
                 name: ${{ matrix.os }} build
                 path: installers/PZero_Linux


            - name: Upload MacOs Build
              if: ${{ matrix.os == 'macos-latest' }}
              uses: actions/upload-artifact@v3
              with:
                 name: ${{ matrix.os }} build
                 path: installers/PZero_Darwin