name: Deploy and Release

on:
    push:
      tags:
        - v*.*.*

jobs:
    # Specify the reusable workflow
    testing:
      uses: ./.github/workflows/release-testing.yml

    deploy:
        strategy:
            matrix:
              # OS we can use to run jobs
              os: [windows-latest, ubuntu-latest, macos-latest]

        runs-on: ${{ matrix.os }}
        # Requiring one or more reusable workflows in needs
        needs: [testing]

        # Steps for deploying a release
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Make executable
              run: |
                pip install pyinstaller
                pyinstaller pzero.spec
                ls

            - name: check path
              run: |
                cd build
                ls

            - name: Upload Build
              uses: actions/upload-artifact@v3
              with:
                 name: ${{ matrix.os }} build
                 path: dist
