name: Unit Testing

on:
  push:
    branches:
      - 'new_2D'

jobs:
  # Linux
  linux-testing:
    name: Linux Unit Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    permissions:
      checks: write
      pull-requests: write


    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create Environment from .yml
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: pzero-testing
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false

      - name: Check Conda version
        run: |
          conda info
          conda list
          
      - name: Test with pytest
        run: |
          py3clean .
          PY_IGNORE_IMPORTMISMATCH=1 pytest --doctest-modules --junitxml=junit/test-results-ubuntu.xml

